### ISSUE TITLE
ロールによって発生したエラーに対応する

### ISSUE THREAD

**Issue by pantasystem** [pantasystem/Milktea#1452]
# 概要
Misskey v13でロール機能が追加され
ロールの制限値をオーバーするとエラーが返ってくるようになった。
その対応を行いたい。

**Comment by pantasystem** [comment]
リスト個数制限オーバー時のエラー
```
{
    "error": {
        "message": "You cannot create user list any more.",
        "code": "TOO_MANY_USERLISTS",
        "id": "0cf21a28-7715-4f39-a20d-777bfdb8d138",
        "kind": "client"
    }
}
```

**Comment by pantasystem** [comment]
リストへのユーザー追加個数オーバー時のエラー
```
{
    "error": {
        "message": "Internal error occurred. Please contact us if the error persists.",
        "code": "INTERNAL_ERROR",
        "id": "5d37dbcb-891e-41ca-a3d6-e690c97775ac",
        "kind": "server",
        "info": {
            "e": {
                "message": "Too many users",
                "code": "Error",
                "stack": "Error: Too many users\n    at UserListService.push (file:///misskey/packages/backend/built/core/UserListService.js:38:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///misskey/packages/backend/built/server/api/endpoints/users/lists/push.js:96:13\n    at async ApiCallService.call (file:///misskey/packages/backend/built/server/api/ApiCallService.js:273:16)"
            }
        }
    }
}
```

**Comment by pantasystem** [comment]
クリップ個数オーバー時のエラー
```
{
    "name": "testestset",
    "description": null,
    "isPublic": false,
    "i": "zgGfXCLHvxmX5TrP"
}
```

**Comment by pantasystem** [comment]
クリップ個数オーバー時
```
{
    "error": {
        "message": "You cannot create clip any more.",
        "code": "TOO_MANY_CLIPS",
        "id": "920f7c2d-6208-4b76-8082-e632020f5883",
        "kind": "client"
    }
}
```

**Comment by pantasystem** [comment]
クリップへのノート追加数オーバー時
```
{
    "error": {
        "message": "You cannot add notes to the clip any more.",
        "code": "TOO_MANY_CLIP_NOTES",
        "id": "f0dba960-ff73-4615-8df4-d6ac5d9dc118",
        "kind": "client"
    }
}
```

**Comment by pantasystem** [comment]
ドライブの容量オーバー時
```
{
    "error": {
        "message": "Cannot upload the file because you have no free space of drive.",
        "code": "NO_FREE_SPACE",
        "id": "d08dbc37-a6a9-463a-8c47-96c32ab5f064",
        "kind": "client"
    }
}
```

**Comment by pantasystem** [comment]
ちなみにロールが非公開な場合自身に割り当てられているroleの値すら取得することができないので
一度リクエストを送ってみてエラーが返ってくるかを確認するまではバリデーションできない

**Comment by pantasystem** [comment]
これってステータスコード何だっけ？

**Comment by pantasystem** [comment]
同一ViewModel内で行われるような処理は、
ダイアログなどでロールによってエラーが発生したことを表示すれば良いが
ノートの投稿などのWorkerなどで実行されている処理はどう表現するのか？という問題がある
